# OS Data Wiper Configuration
# Security-focused configuration for core system operations

# Logging Configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: true
  log_file: "os_data_wiper.log"
  max_log_size_mb: 10
  backup_count: 5

# Security Settings
security:
  require_admin: true
  verify_drive_serial: true
  enable_audit_trail: true
  certificate_generation: true
  
# Drive Detection Settings
hardware:
  enable_hpa_dco_detection: false  # Set to true when fully implemented
  validate_drive_access: true
  detect_removable_media: true
  exclude_system_drive: true  # Safety feature

# Wipe Method Configuration (Step 2 Optimized)
wipe_methods:
  # Step 2 Rule 1: NVMe drives
  default_nvme_primary: "NVME_FORMAT_NVM"  # Faster and more standard than SANITIZE for V1
  default_nvme_fallback: "AES_128_CTR"
  
  # Step 2 Rule 2: SATA SSDs
  default_sata_ssd_primary: "ATA_SECURE_ERASE"
  default_sata_ssd_fallback: "AES_128_CTR"
  
  # Step 2 Rule 3: HDDs, USB, unknown
  default_hdd: "AES_128_CTR"  # Fast, secure software method
  default_usb: "AES_128_CTR"
  default_unknown: "AES_128_CTR"
  default_hdd: "AES-128-CTR"  # Development mode - using encryption instead of DOD_3_PASS
  default_unknown: "NIST_SP800_88"
  fallback_method: "AES-128-CTR"
  
# Performance Settings
performance:
  chunk_size_mb: 64  # For overwrite operations
  verification_passes: 1
  enable_progress_tracking: true
  
# Safety Features
safety:
  require_confirmation: true
  enable_dry_run: true
  create_backup_mbr: false  # Security consideration
  verify_before_wipe: true
